### ISSUE TITLE
Getting can't find soure for Build_doctests error.

### ISSUE THREAD

**Issue by wpoosanguansit** [haskellari/cabal-doctest#47]
Hi,

I followed the doc with the code in Setup.hs taken from the readme.  But I am still getting the following error:

setup: can't find source for Build_doctests in test,
.stack-work/dist/x86_64-linux-nix/Cabal-2.4.0.1/build/doctests/autogen,
.stack-work/dist/x86_64-linux-nix/Cabal-2.4.0.1/build/global-autogen

I am using latest stack with Cabal-2.4.0 and cabal-doctests is defined.  This is running on nixos 18.03 and ghc-8.6.*.  Is there any step missing or any test I could do to see what is missing?  Thanks for your help.

**Comment by phadej** [comment]
@wpoosanguansit you might have a type, do you have your package somewhere publicly viewable?

**Comment by wpoosanguansit** [comment]
@phadej thanks for your help.  Unfortunately, we don't have it in a publicly viewable project. Below are the two package and stack yaml files we are using.  Thanks again for  your help.

[package.yaml.txt](https://github.com/phadej/cabal-doctest/files/3055588/package.yaml.txt)
[stack.yaml.txt](https://github.com/phadej/cabal-doctest/files/3055589/stack.yaml.txt)

**Comment by phadej** [comment]
I don't see anything obviously wrong with those.

You could try a version in https://github.com/phadej/cabal-doctest/pull/48 which would log the location of generated `Build_doctests` file. (I though have no idea how make `stack` to make custom setup verbose, `--cabal-verbose` doesn't seem to do the trick). Or you could try to `find . -name 'Build_depends.hs` to see if it's created at all.

**Comment by wpoosanguansit** [comment]
find didn't return any result.  So the file was not generated at all I think.  Also, i did use the commit you mentioned.  I also didn't see any print out that is different from my earlier stack test runs.  Any other suggestions?  Thanks.

**Comment by phadej** [comment]
- is generated twinflower.cabal with `build-type: Custom`
- how does your Setup.hs looks like

**Comment by wpoosanguansit** [comment]
{-# LANGUAGE CPP #-}
{-# OPTIONS_GHC -Wall #-}

module Main (main) where

#ifndef MIN_VERSION_cabal_doctest
#define MIN_VERSION_cabal_doctest(x,y,z) 0
#endif

#if MIN_VERSION_cabal_doctest(1,0,0)

import Distribution.Extra.Doctest ( defaultMainWithDoctests )
import Data.ProtoLens.Setup

main :: IO ()
main = do
    defaultMainGeneratingProtos "src/System/Proto"
    defaultMainWithDoctests "doctests"

#else

#ifdef MIN_VERSION_Cabal
-- If the macro is defined, we have new cabal-install,
-- but for some reason we don't have cabal-doctest in package-db
--
-- Probably we are running cabal sdist, when otherwise using new-build
-- workflow
#warning You are configuring this package without cabal-doctest installed. \
         The doctests test-suite will not work as a result. \
         To fix this, install cabal-doctest before configuring.
#endif

import Distribution.Simple
import Data.ProtoLens.Setup

main :: IO ()
main = do 
    defaultMain
    defaultMainGeneratingProtos "src/System/Proto"

#endif

I basically copy this from the example you have.  Any suggestion?

**Comment by phadej** [comment]
```haskell
main = do
    defaultMainGeneratingProtos "src/System/Proto"
    defaultMainWithDoctests "doctests"
```

That's definitely incorrect. You might take a look into adding hooks with http://hackage.haskell.org/package/cabal-doctest-1.0.6/docs/Distribution-Extra-Doctest.html#v:addDoctestsUserHook

Look how `defaultMainWithDoctests` or `defaultMainAutoconfWithDoctests` are implemented.

**Comment by wpoosanguansit** [comment]
I do see this in the doc:

```
defaultMainWithDoctests Source #

:: String	
doctests test-suite name
-> IO ()	 
A default main with doctests:

import Distribution.Extra.Doctest
       (defaultMainWithDoctests)

main :: IO ()
main = defaultMainWithDoctests "doctests"
```

And I do have this:

```
import Distribution.Extra.Doctest ( defaultMainWithDoctests )
import Data.ProtoLens.Setup

main :: IO ()
main = do
    defaultMainGeneratingProtos "src/Turgenev/System/Proto"
    defaultMainWithDoctests "doctests"
```
defaultMainWithDoctests "doctests" will get run, right?  I have to apologize that I didn't see what is missing yet.  Thanks for your help.

**Comment by phadej** [comment]
I'm pretty sure that `defaultMainWithDoctests "doctests"` isn't run. Or if it is, it doesn't do anything reasonable.

**Comment by alissa-tung** [comment]
Whats your test-suite name for doctests in the Cabal file? In the pkg doc case, it is "doctests".

**Comment by wpoosanguansit** [comment]
I am so sorry @alissa-tung that I have stop working on the code awhile back and I totally lost the hd that this project was on from encryption.  Thanks for your help.

**Comment by alissa-tung** [comment]
> I am so sorry @alissa-tung that I have stop working on the code awhile back and I totally lost the hd that this project was on from encryption.  Thanks for your help.

You're welcome and sorry to hear that. I ran into this issue because I initially use the name in the example instead the test-suite of the package I am working on and after I made CI passing I thought I can help if it can be the reason in this issue. Hoping someone who indexed the issues in the future can save some time :)
