### ISSUE TITLE
Deprecation plan

### ISSUE THREAD

**Issue by sgraf812** [haskellari/cabal-doctest#59]
The library mentions the following plan for deprecation

> There is an issue in the [Cabal issue tracker](https://github.com/haskell/cabal/issues/2327) about adding cabal doctest command. After that command is implemented, this library will be deprecated.

But
- That issue has already been closed (although there is only `cabal v1-doctest`)
- This library is useful independently of `doctest`. It's probably easy to say so in retrospect, but I think it should have been given a different name. I like it as a maintained replacement of https://hackage.haskell.org/package/cabal-toolkit.

I use this to initialise the GHC API so that I can compile Haskell code to Core. I used cabal-toolkit before, but that didn't work well with `doctest`. Hmm. Maybe I should use `hie-bios` instead? :thinking:
Edit: No, I don't think that would work. There's no way I can make sure that the GHC versions match, which is trivial with cabal-doctest and cabal-toolkit. 

Regardless, I think it would be good to update that note.

**Comment by andreasabel** [comment]
I removed the reference to `cabal doctest` in 1.0.9.
