### ISSUE TITLE
Add constraint `Cabal >=1.24` to example in README

### ISSUE THREAD

**Issue by andreasabel** [haskellari/cabal-doctest#66]
@phadej, thanks for this tool, it solved my problem to communicate the preprocessor(happy/alex)-generated files to my doctests-main in a robust way.

In the light of your explanation at https://github.com/haskell-CI/haskell-ci/issues/81#issuecomment-303954282 
> custom-setup section is supported with Cabal >= 1.24

it may make sense to include the constraint `Cabal >=1.24` in your simple example and in the README.
At least this constraint make my build succeed:
- broken: https://github.com/BNFC/bnfc/runs/1594385248?check_suite_focus=true
  `Warning: ignoring unknown section type: custom-setup`
- fixed: https://github.com/BNFC/bnfc/runs/1594499990?check_suite_focus=true

I can prepare a PR.

**Comment by phadej** [comment]
You understood that description in wrong way.

If you want to force having `Cabal` which would actually interpret `custom-setup` section, you need to use `cabal-version: 1.24`. Adding the bound to `setup-depends` won't do anything if someone uses old `cabal-install`, it will happily ignore whole section.

**Comment by andreasabel** [comment]
Probably I got the wrong message from this comment: https://github.com/haskell-CI/haskell-ci/issues/81#issuecomment-304087288
> ... setting `setup-depends: Cabal >= 1.24` makes it work.

@phadej wrote:
> If you want to force having Cabal which would actually interpret custom-setup section, you need to use cabal-version: 1.24 (or later).

That makes a lot of sense...
