### ISSUE TITLE
Publish a version that accepts Cabal 3.6

### ISSUE THREAD

**Issue by tchoutri** [haskellari/cabal-doctest#74]
Hi @andreasabel, could we have a version that supports Cabal 3.6 on Hackage? :)

**Comment by andreasabel** [comment]
@tchoutri I just released 1.0.9.  Can you please check if it works for you?

**Comment by tchoutri** [comment]
@andreasabel It does, thank you very much!

**Comment by andreasabel** [comment]
Great!
